export const ListingsData = [
    {
        address: "1C Mayfield Avenue",
        district: "D15 East Coast / Marine Parade",
        landSize: "4400",
        builtUp: "10590",
        askingPrice: "14500000",
        lift: "True",
        pool: "True",
        features: ["Lift", "Pool"], 
        developer: "Treasure Development (Meyer) Pte Ltd",
        imageUrl: require('../../assets/1C_Mayfield_Avenue.jpg'),
    },
    {
        address: "1C Mayfield Avenue",
        district: "D15 East Coast / Marine Parade",
        landSize: "4400",
        builtUp: "10590",
        askingPrice: "14500000",
        lift: "False",
        pool: "True",
        features: ["Pool"], 
        developer: "Treasure Development (Meyer) Pte Ltd",
        imageUrl: require('../../assets/1C_Mayfield_Avenue.jpg'),
    },
    {
        address: "1C Mayfield Avenue",
        district: "D15 East Coast / Marine Parade",
        landSize: "4400",
        builtUp: "10590",
        askingPrice: "14500000",
        lift: "False",
        pool: "False",
        features: [],
        developer: "Treasure Development (Meyer) Pte Ltd",
        imageUrl: require('../../assets/1C_Mayfield_Avenue.jpg'),
    },
    {
        address: "45A Greenmead Avenue",
        district: "D11 Newton / Novena",
        landSize: "3092",
        builtUp: "6182",
        askingPrice: "10825000",
        lift: "False",
        pool: "True",
        features: ["Pool"], 
        developer: "Pinnacle Land Pte Ltd",
        imageUrl: require('../../assets/45A_Greenmead_Avenue.jpg')
    },
    {
        address: "41 Goldhill Avenue",
        district: "D11 Newton / Novena",
        landSize: "4752",
        builtUp: "8347",
        askingPrice: "18200000",
        lift: "False",
        pool: "True",
        features: ["Lift"], 
        developer: "A-Home Development Pte Ltd",
        imageUrl: require('../../assets/41_Goldhill_Avenue.jpg')
    },
    {
        address: "2 Park Vale",
        district: "D11 Newton / Novena",
        landSize: "4340",
        builtUp: "9659",
        askingPrice: "17700000",
        lift: "True",
        pool: "False",
        features: ["Lift"], 
        developer: "Park Vale Land Pte Ltd",
        imageUrl: require('../../assets/2_Park_Vale.jpg')
    },
    {
        address: "145 Holland Road",
        district: "D10 Tanglin / Holland / Bukit Timah",
        landSize: "2593",
        builtUp: "5700",
        askingPrice: "8100000",
        lift: "True",
        pool: "False",
        features: ["Lift"], 
        developer: "Wah Khiaw Developments Pte Ltd",
        imageUrl: require('../../assets/145_Holland_Road.jpg')
    },
]